[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/llm"
  to = "/.netlify/functions/llm"
  status = 200
  force = true
