[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Redirect frontend routes to index.html (fix SPA 404s)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API route → function
[[redirects]]
  from = "/api/llm"
  to = "/.netlify/functions/llm"
  status = 200
  force = true

