[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# API route -> function (must come BEFORE catch-all)
[[redirects]]
  from = "/api/llm"
  to = "/.netlify/functions/llm"
  status = 200
  force = true

# SPA support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
